###Frobenius Norm

In [49]:
#menggunakan numpy, pytoch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm
import numpy as np

In [50]:
X = np.array([[7,9,0],[9,7,0],[7,7,7]])
X

array([[7, 9, 0],
       [9, 7, 0],
       [7, 7, 7]])

In [51]:
X.shape

(3, 3)

In [52]:
(7**2 + 9**2 + 0**2 + 9**2 + 7**2 + 0**2 + 7**2 + 7**2 + 7**2)**(1/2)

20.174241001832016

In [53]:
(X[0,0]**2 + X[0,1]**2 + X[0,2]**2 + X[1,0]**2 + X[1,1]**2 + X[1,2]**2 + X[2,0]**2 + X[2,1]**2 + X[2,2]**2)**(1/2)

np.float64(20.174241001832016)

In [54]:
np.linalg.norm(X)

np.float64(20.174241001832016)

###Torch

In [55]:
#menggunakan numpy, pytoch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm
import torch

In [56]:
X_pt = torch.tensor([[7,9,0],[9,7,0],[7,7,7.]])
X

array([[7, 9, 0],
       [9, 7, 0],
       [7, 7, 7]])

In [57]:
torch.norm(X_pt)

tensor(20.1742)

###TensorFlow

In [58]:
#menggunakan numpy, pytoch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm
import tensorflow as tf

In [59]:
X_tf = tf.Variable([[7,9,0],[9,7,0],[7,7,7.]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[7., 9., 0.],
       [9., 7., 0.],
       [7., 7., 7.]], dtype=float32)>

In [60]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=20.174240112304688>