In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#buat matrix X ukuran 2x2 menggunakan numpy
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [ ]:
#buat invers dari matrix X dan beri nama Xinv menggunakan numpy
Xinv = np.linalg.inv(X)
Xinv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
#kalikan X dengan Xinv menggunakan numpy
np.dot(Xinv, X)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [ ]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [ ]:
np.dot(Xinv, X)

array([[1.00000000e+00, 3.33066907e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [ ]:
torch.inverse(torch.tensor([[4, 2], [-5, -3.]])) # float type

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]])

In [ ]:
tf.linalg.inv(tf.Variable([[4, 2], [-5, -3.]])) # also float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4999998,  0.9999998],
       [-2.4999995, -1.9999996]], dtype=float32)>