In [1]:
import torch #lakukan perhitungan soal excercise menggunakan collab

In [2]:
M_q = torch.tensor([[10, 9, 8], [11, 22, 33], [1, 2, 3]])
M_q

tensor([[10,  9,  8],
        [11, 22, 33],
        [ 1,  2,  3]])

In [3]:
V_q = torch.tensor([[0, 20, 40], [50, 30, 10]]).T
V_q

tensor([[ 0, 50],
        [20, 30],
        [40, 10]])

In [4]:
torch.matmul(M_q, V_q)

tensor([[ 500,  850],
        [1760, 1540],
        [ 160,  140]])