###Matrix Multiplication

In [165]:
# buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
import numpy as np

In [166]:
A = np.array([[7,9,0],[9,7,0]])
A

array([[7, 9, 0],
       [9, 7, 0]])

In [167]:
b = np.array([[0],[7],[9]])
b

array([[0],
       [7],
       [9]])

In [168]:
# tampilkan ukuran matrix A dan vector b
A.shape

(2, 3)

In [169]:
b.shape

(3, 1)

In [170]:
# kalikan matrix A dengan vector b
np.dot(A, b)

array([[63],
       [49]])

In [171]:
# buat matrix B dengan ukuran 3x3 menggunakan numpy
B = np.array([[7,9,0],[9,7,0],[7,7,7]])
B

array([[7, 9, 0],
       [9, 7, 0],
       [7, 7, 7]])

In [172]:
# kalikan matrix A dengan matrix B
np.dot(A, B)

array([[130, 126,   0],
       [126, 130,   0]])

In [173]:
# buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?

# np.dot(B, A)

# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# /tmp/ipykernel_1722/2086928075.py in <cell line: 0>()
#       1 # buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
# ----> 2 np.dot(B, A)
#
# ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

''' Jadi perkalian matrix tidak bersifat komutatif dikarenakan perkalian
matrix A (2x3) dan perkalian matrix B (3x3) bisa dilakukan karena memenuhi
bentuk yang memungkinkan untuk dikalikan, tetapi tidak dengan Matrix B (3x3)
dan Matrix A (2x3) karena tidak memenuhi syarat perkalian matrix.
'''

' Jadi perkalian matrix tidak bersifat komutatif dikarenakan perkalian \nmatrix A (2x3) dan perkalian matrix B (3x3) bisa dilakukan karena memenuhi \nbentuk yang memungkinkan untuk dikalikan, tetapi tidak dengan Matrix B (3x3) \ndan Matrix A (2x3) karena tidak memenuhi syarat perkalian matrix.\n'

###Pytorch

In [174]:
# buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
import torch

In [175]:
A_pt = torch.tensor([[7,9,0],[9,7,0]])
A_pt

tensor([[7, 9, 0],
        [9, 7, 0]])

In [176]:
b_pt = torch.tensor([[0],[7],[9]])
b_pt

tensor([[0],
        [7],
        [9]])

In [177]:
# tampilkan ukuran matrix A dan vector b
A_pt.shape

torch.Size([2, 3])

In [178]:
b_pt.shape

torch.Size([3, 1])

In [179]:
# kalikan matrix A_pt dengan vector b_pt
torch.matmul(A_pt, b_pt)

tensor([[63],
        [49]])

In [180]:
# buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
B_pt = torch.tensor([[7,9,0],[9,7,0],[7,7,7]])
B_pt

tensor([[7, 9, 0],
        [9, 7, 0],
        [7, 7, 7]])

In [181]:
# kalikan matrix A_pt dengan matrix B_pt
torch.matmul(A_pt, B_pt)

tensor([[130, 126,   0],
        [126, 130,   0]])

In [182]:
# buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?

# torch.matmul(B_pt, A_pt)

# ---------------------------------------------------------------------------
# RuntimeError                              Traceback (most recent call last)
# /tmp/ipykernel_1722/1494789641.py in <cell line: 0>()
#       1 # buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
# ----> 2 torch.matmul(B_pt, A_pt)
#
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 2x3)

''' Jadi perkalian matrix tidak bersifat komutatif dikarenakan perkalian
matrix A (2x3) dan perkalian matrix B (3x3) bisa dilakukan karena memenuhi
bentuk yang memungkinkan untuk dikalikan, tetapi tidak dengan Matrix B (3x3)
dan Matrix A (2x3) karena tidak memenuhi syarat perkalian matrix.
'''

' Jadi perkalian matrix tidak bersifat komutatif dikarenakan perkalian \nmatrix A (2x3) dan perkalian matrix B (3x3) bisa dilakukan karena memenuhi \nbentuk yang memungkinkan untuk dikalikan, tetapi tidak dengan Matrix B (3x3) \ndan Matrix A (2x3) karena tidak memenuhi syarat perkalian matrix.\n'

###TensorFlow

In [183]:
# buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
import tensorflow as tf

In [184]:
A_tf = tf.Variable([[7,9,0],[9,7,0]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[7, 9, 0],
       [9, 7, 0]], dtype=int32)>

In [185]:
b_tf = tf.Variable([[0],[7],[9]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[0],
       [7],
       [9]], dtype=int32)>

In [186]:
# tampilkan ukuran matrix A dan vector b
A_tf.shape

TensorShape([2, 3])

In [187]:
tf.shape(A_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [188]:
b_tf.shape

TensorShape([3, 1])

In [189]:
tf.shape(b_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 1], dtype=int32)>

In [190]:
# kalikan matrix A_tf dengan vector b_tf
tf.linalg.matmul(A_tf, b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[63],
       [49]], dtype=int32)>

In [191]:
tf.matmul(A_tf,b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[63],
       [49]], dtype=int32)>

In [192]:
# buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
B_tf = tf.Variable([[7,9,0],[9,7,0],[7,7,7]])
B_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[7, 9, 0],
       [9, 7, 0],
       [7, 7, 7]], dtype=int32)>

In [193]:
# kalikan matrix A_tf dengan matrix B_tf
tf.linalg.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[130, 126,   0],
       [126, 130,   0]], dtype=int32)>

In [194]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[130, 126,   0],
       [126, 130,   0]], dtype=int32)>

In [195]:
# buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?

# tf.linalg.matmul(B_tf, A_tf)

# ---------------------------------------------------------------------------
# InvalidArgumentError                      Traceback (most recent call last)
# /tmp/ipykernel_1722/1493613797.py in <cell line: 0>()
#       1 # buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
# ----> 2 tf.linalg.matmul(B_tf, A_tf)
#
# 2 frames
# /usr/local/lib/python3.12/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
#    6004 def raise_from_not_ok_status(e, name) -> NoReturn:
#    6005   e.message += (" name: " + str(name if name is not None else ""))
# -> 6006   raise core._status_to_exception(e) from None  # pylint: disable=protected-access
#    6007
#    6008
#
# InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,3], In[1]: [2,3] [Op:MatMul] name:

''' Jadi perkalian matrix tidak bersifat komutatif dikarenakan perkalian
matrix A (2x3) dan perkalian matrix B (3x3) bisa dilakukan karena memenuhi
bentuk yang memungkinkan untuk dikalikan, tetapi tidak dengan Matrix B (3x3)
dan Matrix A (2x3) karena tidak memenuhi syarat perkalian matrix.
'''

' Jadi perkalian matrix tidak bersifat komutatif dikarenakan perkalian \nmatrix A (2x3) dan perkalian matrix B (3x3) bisa dilakukan karena memenuhi \nbentuk yang memungkinkan untuk dikalikan, tetapi tidak dengan Matrix B (3x3) \ndan Matrix A (2x3) karena tidak memenuhi syarat perkalian matrix.\n'