## Matrix Simetris

In [1]:
import numpy as np

In [2]:
# membuat matix simetris ukuran 3x3
X_sym = np.array([[2, 3, 6], [3, 4, 5], [6, 5, 9]])
X_sym

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]])

In [3]:
# melakukan transportsisi matrix
X_sym.T

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]])

In [4]:
# membuktikan bahwa Matrix X simetris
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Matrix Identitas

In [5]:
import torch

In [18]:
# membuat matrix identitas ukuran 4x4 dengan menggunakan pytorch
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [16]:
# membuat vector b_pt ukuran 4x1 dengan menggunakan pytorch
b_pt = torch.tensor([[1], [2], [3], [4]])
b_pt

tensor([[1],
        [2],
        [3],
        [4]])

In [19]:
# mengkalikan matriks I dengan vector b_pt
torch.matmul(I, b_pt)

tensor([[1],
        [2],
        [3],
        [4]])