In [ ]:
import numpy as np
import torch
import tensorflow as tf

### Matrix X

In [ ]:
# membuat matrix X dengan ukuran 2x3
X = np.array([[25, 2, 3], [5, 26, 7]])
X

array([[25,  2,  3],
       [ 5, 26,  7]])

In [ ]:
# membuat matrix X_pt dengan pytorch ukuran 2x3
X_pt = torch.tensor([[25, 2, 3], [5, 26, 7]])
X_pt

tensor([[25,  2,  3],
        [ 5, 26,  7]])

In [ ]:
# membuat matrix X_tf dengan tensorflow ukuran 2x3
X_tf = tf.Variable([[25, 2, 3], [5, 26, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25,  2,  3],
       [ 5, 26,  7]], dtype=int32)>

Operasi perkalian

In [ ]:
# melakukan perkalian matrix X dengan skalar
X*2

array([[50,  4,  6],
       [10, 52, 14]])

In [ ]:
# melakukan perkalian matrix X_pt pytorch dengan skalar
X_pt*4

tensor([[100,   8,  12],
        [ 20, 104,  28]])

In [ ]:
# melakukan perkalian matrix X_tf tensorflow dengan skalar
X_tf*7

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[175,  14,  21],
       [ 35, 182,  49]], dtype=int32)>

operasi penjumlahan

In [ ]:
# melakukan perjumlahan matrix X dengan skalar
X + 5

array([[30,  7,  8],
       [10, 31, 12]])

In [ ]:
# melakukan penjumlahan matrix X_pt pytorch dengan skalar
X_pt + 7

tensor([[32,  9, 10],
        [12, 33, 14]])

In [ ]:
# melakukan penjumlahan matrix X_tf tensorflow dengan skalar
X_tf + 11

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[36, 13, 14],
       [16, 37, 18]], dtype=int32)>

Operasi Pengurangan

In [ ]:
# melakukan pengurangan Matrix X dengan skalar
X - 2

array([[23,  0,  1],
       [ 3, 24,  5]])

In [ ]:
# melakukan pegurangan Matrix X_pt pytorch dengan skalar
X_pt - 18

tensor([[  7, -16, -15],
        [-13,   8, -11]])

In [ ]:
# melakukan pengurangan Matrix
X_tf - 6

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[19, -4, -3],
       [-1, 20,  1]], dtype=int32)>

### Matrix Y

In [36]:
# membuat Matrix Y dengan ukuran 2x3
Y = np.array([[5, 6, 3], [7, 13, 5]])
Y

array([[ 5,  6,  3],
       [ 7, 13,  5]])

In [37]:
# membuat matrix Y_pt dengan pytorch ukuran 2x3
Y_pt = torch.tensor([[5, 6, 3], [7, 13, 5]])
Y_pt

tensor([[ 5,  6,  3],
        [ 7, 13,  5]])

In [38]:
# membuat matrix Y_tf dengan tensorflow ukuran 2x3
Y_tf = tf.Variable([[5, 6, 3], [7, 13, 5]])
Y_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 5,  6,  3],
       [ 7, 13,  5]], dtype=int32)>

In [39]:
# mengalikan matrix X dengan Y
X * Y

array([[125,  12,   9],
       [ 35, 338,  35]])

In [40]:
# mengalikan matrix X_pt dengan Y_pt
X_pt * Y_pt

tensor([[125,  12,   9],
        [ 35, 338,  35]])

In [41]:
# mengalikan matrix X_tf dengan Y_tf
X_tf * Y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[125,  12,   9],
       [ 35, 338,  35]], dtype=int32)>