## Segment 2: Common Tensor Operations

### Tensor Transposition

In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [9]:
# Use array() with nested brackets:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [10]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

# using torch

In [11]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [14]:
X_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

using tensorflow

In [13]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [15]:
tf.transpose(X_tf) # less Pythonic

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]], dtype=int32)>