numpy

In [80]:
import numpy as np #buat vector x dan y dengan ukuran 1x3 menggunakan numpy

In [81]:
x = np.array([19, 8, 2])
x

array([19,  8,  2])

In [82]:
y = np.array([22, 11, 4])
y

array([22, 11,  4])

In [83]:
19*22 + 8*11 + 2*4 #hitung perkalian dot product antara vector x dan vector y
                   #Manual

514

In [84]:
np.dot(x, y) #NumPy

np.int64(514)

pytorch

In [85]:
import torch #buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch

In [86]:
x_pt = torch.tensor([19, 8, 2])
x_pt

tensor([19,  8,  2])

In [87]:
y_pt = torch.tensor([22, 11, 4])
y_pt

tensor([22, 11,  4])

In [88]:
torch.dot(x_pt, y_pt) #hitung perkalian dot product antara vector x_pt dan vector y_pt

tensor(514)

In [89]:
torch.dot(torch.tensor([19, 8, 2.]), torch.tensor([22, 11, 4.]))

tensor(514.)

tensorflow

In [90]:
import tensorflow as tf #buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow

In [91]:
x_tf = tf.Variable([19, 8, 2])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([19,  8,  2], dtype=int32)>

In [92]:
y_tf = tf.Variable([22, 11, 4])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([22, 11,  4], dtype=int32)>

In [93]:
tf.reduce_sum(tf.multiply(x_tf, y_tf)) #hitung perkalian dot product antara vector x_tf dan vector y_tf

<tf.Tensor: shape=(), dtype=int32, numpy=514>

Perhitungan Excercise

In [94]:
import numpy as np #SOAL NOMOR 1

In [95]:
Y = np.array([[42, 4, 7, 49],
              [-99, -3, 17, -22]])

In [96]:
Y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 49, -22]])

In [97]:
A = np.array([[25, 10], #SOAL NOMOR 2
              [-2, 1]])

In [98]:
B = np.array([[-1, 7],
              [10, 8]])

In [99]:
A * B

array([[-25,  70],
       [-20,   8]])

In [100]:
w = np.array([-1, 2, -2]) #SOAL NOMOR 3

In [101]:
x = np.array([5, 10, 0])

In [102]:
np.dot(w, x)

np.int64(15)