###Matrix Tensors

In [ ]:
import numpy as np

In [ ]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[70,90],[97,79],[70,90]])
X

array([[70, 90],
       [97, 79],
       [70, 90]])

In [ ]:
# tampilkan ukuran dari matrix X
X.shape

(3, 2)

In [ ]:
X.size

6

In [ ]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X [:,0]

array([70, 97, 70])

In [ ]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X [1,:]

array([97, 79])

### Pytorch

In [ ]:
import torch
import tensorflow as tf

In [ ]:
X_pt = torch.tensor([[70,90],[79,97],[90,70]])
X_pt

tensor([[70, 90],
        [79, 97],
        [90, 70]])

In [ ]:
# tampilkan ukuran dari matrix X
X_pt.shape

torch.Size([3, 2])

In [ ]:
X_pt.size

<function Tensor.size>

In [ ]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X_pt [:,0]

tensor([70, 79, 90])

In [ ]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X_pt [1,:]

tensor([79, 97])

### Tensorflow

In [ ]:
X_tf = tf.Variable([[70,90],[79,97],[90,70]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[70, 90],
       [79, 97],
       [90, 70]], dtype=int32)>

In [ ]:
# tampilkan ukuran dari matrix X
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [ ]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X_tf [:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([70, 79, 90], dtype=int32)>

In [ ]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X_tf [1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([79, 97], dtype=int32)>