###Norms and Unit Vectors

In [ ]:
import numpy as np

In [ ]:
# buat vector x dengan ukuran 3x1
x = np.array([79,7,9])
x

array([79,  7,  9])

In [ ]:
# hitung nilai L2 norm dari vector x
(x[0]**2 + x[1]**2 + x[2]**2)**(1/2)

np.float64(79.81854421122951)

In [ ]:
np.linalg.norm(x)

np.float64(79.81854421122951)

In [ ]:
# buat vector v dengan elemen (3,4)
v = np.array([3,4])
v

array([3, 4])

In [ ]:
# hitung nilai L2 norm dari vector v
(v[0]**2 + v[1]**2)**(1/2)

np.float64(5.0)

In [ ]:
norm = np.linalg.norm(v)
norm

np.float64(5.0)

In [ ]:
# tampilkan unit vector dari vector v
unit_v = v / norm
unit_v

array([0.6, 0.8])

In [ ]:
# hitung panjang unit vector dari vector v
np.linalg.norm(unit_v)

np.float64(1.0)