###Vectors and Vector Transposition

In [248]:
import numpy as np

In [249]:
# buat vector x dengan ukuran 3x1
x = np.array([0.79,7,9])
x

array([0.79, 7.  , 9.  ])

In [250]:
# hitung panjang vector x
len(x)

3

In [251]:
# tampilkan ukuran vector x
x.shape

(3,)

In [252]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [253]:
# akses elemen pertama dari vector x
x[0]

np.float64(0.79)

In [254]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.float64

###Vector Transpotition

In [255]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x = np.array([[0.79,7,9]])
x_t = x.T
x_t

array([[0.79],
       [7.  ],
       [9.  ]])

In [256]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3, 1)

In [257]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([0,7,9])
y

array([0, 7, 9])

In [258]:
y.shape

(3,)

In [259]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[0,7,9]])
y_t = y.T
y_t

array([[0],
       [7],
       [9]])

In [260]:
# tampilkan ukuran dari vector y_t
y_t.shape

(3, 1)

###Pytorch

In [261]:
import torch

In [262]:
# buat vector x dengan ukuran 3x1
x_pt = torch.tensor([0.79,7,9])
x_pt

tensor([0.7900, 7.0000, 9.0000])

In [263]:
# hitung panjang vector x
len(x_pt)

3

In [264]:
# tampilkan ukuran vector x
x_pt.shape

torch.Size([3])

In [265]:
x_pt.size

<function Tensor.size>

In [266]:
# tampilkan tipe data dari vector x
type(x_pt)

torch.Tensor

In [267]:
# akses elemen pertama dari vector x
x_pt[0]

tensor(0.7900)

In [268]:
# tampilkan tipe data elemen pertama dari vector x
type(x_pt[0])

torch.Tensor

In [269]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_pt = torch.tensor([[0.79,7,9]])
x_pt_t = x_pt.T
x_pt_t

tensor([[0.7900],
        [7.0000],
        [9.0000]])

In [270]:
# tampilkan ukuran dari vector x_t
x_pt_t.shape

torch.Size([3, 1])

In [271]:
y_pt = torch.tensor([0,7,9])
y_pt

tensor([0, 7, 9])

In [272]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_pt = torch.tensor([0,7,9])
y_t_pt = y.T
y_t_pt

array([[0],
       [7],
       [9]])

In [273]:
# tampilkan ukuran dari vector y_t
y_t_pt.shape

(3, 1)

###Tensorflow

In [274]:
import tensorflow as tf

In [275]:
# buat vector x dengan ukuran 3x1
x_tf = tf.Variable([0,7,9])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 7, 9], dtype=int32)>

In [276]:
# hitung panjang vector x
tf.rank(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [277]:
# tampilkan ukuran vector x
tf.shape(x_tf)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [278]:
# tampilkan tipe data dari vector x
type(x_tf)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [279]:
# akses elemen pertama dari vector x
x_tf[0]

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [280]:
# tampilkan tipe data elemen pertama dari vector x
type(x_tf[0])

tensorflow.python.framework.ops.EagerTensor

In [281]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_tf = tf.Variable([[0,7,9]])
x_tf_t = tf.transpose(x_tf)
x_tf_t

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[0],
       [7],
       [9]], dtype=int32)>

In [282]:
# tampilkan ukuran dari vector x_t
tf.shape(x_tf_t)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 1], dtype=int32)>

In [283]:
y_tf = tf.Variable([0,7,9])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 7, 9], dtype=int32)>

In [284]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_tf = tf.Variable([[0,7,9]])
y_tf_t = tf.transpose(y_tf)
y_tf_t

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[0],
       [7],
       [9]], dtype=int32)>

In [285]:
# tampilkan ukuran dari vector x_t
tf.shape(y_tf_t)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 1], dtype=int32)>